services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopping_app_prod
    restart: unless-stopped
    ports:
      - "8082:82"  # host port 8082 -> container port 82
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - APP_NAME=${APP_NAME}
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=${APP_URL}
    depends_on:
      - mysql
      - redis
    networks:
      - shopping_network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: shopping_mysql_prod
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shopping_network

  # Redis for Caching
  redis:
    image: redis:7-alpine
    container_name: shopping_redis_prod
    restart: unless-stopped
    ports:
      - "6380:6379"  # host port 6380 -> container 6379
    volumes:
      - redis_data_prod:/data
    networks:
      - shopping_network

volumes:
  mysql_data_prod:
    driver: local
  redis_data_prod:
    driver: local

networks:
  shopping_network:
    driver: bridge
